const base = `${import.meta.env.BASE_URL}assets/acko-drive-details`;

export const carDetailsAssets = {
  statusBattery: `${base}/status-battery.svg`,
  statusWifi1: `${base}/status-wifi-1.svg`,
  statusWifi2: `${base}/status-wifi-2.svg`,
  statusWifi3: `${base}/status-wifi-3.svg`,
  statusCellular: `${base}/status-cellular.svg`,
  iconBack: `${base}/icon-back.svg`,
  iconLocation: `${base}/icon-location.svg`,
  heroSeltos: `${base}/hero-seltos.png`,
  askSidGrid: `${base}/ask-sid-grid.png`,
  askSidAvatar: `${base}/ask-sid-avatar.png`,
  askSidGlow: `${base}/ask-sid-glow.svg`,
  askSidChipGlow: `${base}/ask-sid-chip-glow.svg`,
  askSidLogo: `${base}/ask-sid-logo.svg`,
  askSidGlowLeft: `${base}/ask-sid-glow-left.svg`,
  askSidGlowInput: `${base}/ask-sid-glow-input.svg`,
  iconCompareCars: `${base}/icon-compare-cars.svg`,
  iconChevronRight: `${base}/icon-chevron-right.svg`,
  iconChevronRight16: `${base}/icon-chevron-right-16.svg`,
  iconChevronRight20: `${base}/icon-chevron-right-20.svg`,
  iconLightning: `${base}/icon-lightning.svg`,
  iconClock: `${base}/icon-clock.svg`,
  iconGallery: `${base}/icon-gallery.svg`,
  iconPlay: `${base}/icon-play.svg`,
  iconPlayExpert: `${base}/icon-play-expert.svg`,
  iconExclusive: `${base}/icon-exclusive.svg`,
  iconExclusiveBadge: `${base}/icon-exclusive-badge.svg`,
  iconStarOn: `${base}/icon-star-on.svg`,
  iconStarOff: `${base}/icon-star-off.svg`,
  iconStarRating: `${base}/icon-star-rating.svg`,
  iconChevronDown: `${base}/icon-chevron-down.svg`,
  iconChevronRightWhite: `${base}/icon-chevron-right-white.svg`,
  iconValue: `${base}/icon-value.svg`,
  iconSpace: `${base}/icon-space.svg`,
  iconReliability: `${base}/icon-reliability.svg`,
  iconComfort: `${base}/icon-comfort.svg`,
  ringTrack: `${base}/ring-track.svg`,
  ringValue: `${base}/ring-value.svg`,
  ringSpace: `${base}/ring-space.svg`,
  ringReliability: `${base}/ring-reliability.svg`,
  iconGncapAdult: `${base}/icon-gncap-adult.svg`,
  iconGncapChild: `${base}/icon-gncap-child.svg`,
  iconEdit: `${base}/icon-edit.svg`,
  iconShortlist: `${base}/icon-shortlist.svg`,
  iconAckoMark: `${base}/icon-acko-mark.svg`,
  iconAckoWord: `${base}/icon-acko-word.svg`,
  featureOrvm: `${base}/feature-orvm.png`,
  featureInterior: `${base}/feature-interior.png`,
  featureNight: `${base}/feature-night.png`,
  swatches: [
    `${base}/swatch-1.png`,
    `${base}/swatch-2.png`,
    `${base}/swatch-3.png`,
    `${base}/swatch-4.png`,
    `${base}/swatch-5.png`,
    `${base}/swatch-6.png`,
  ],
  ncapVideo: `${base}/ncap-video.png`,
  colorPewter: `${base}/color-pewter.png`,
  colorIntenseRed: `${base}/color-intense-red.png`,
  colorImperialBlue: `${base}/color-imperial-blue.png`,
  colorAuroraBlack: `${base}/color-aurora-black.png`,
  colorGlacierWhite: `${base}/color-glacier-white.png`,
  colorGravityGrey: `${base}/color-gravity-grey.png`,
  rivalNexon: `${base}/rival-nexon.png`,
  rivalCreta: `${base}/rival-creta.png`,
  rival3xo: `${base}/rival-3xo.png`,
  dimSide: `${base}/dim-side.png`,
  dimSilhouette: `${base}/dim-silhouette.png`,
  dimFront: `${base}/dim-front.png`,
  dimCard: `${base}/dim-card.png`,
  compareSeltos: `${base}/compare-seltos.png`,
  compareCreta: `${base}/compare-creta.png`,
  expertVideo1: `${base}/expert-video-1.png`,
  expertVideo2: `${base}/expert-video-2.png`,
  expertVideo3: `${base}/expert-video-3.png`,
  expertVideo4: `${base}/expert-video-4.png`,
} as const;
